// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veilingklok.Infrastructure.Database;

#nullable disable

namespace Veilingklok.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251209053424_FixEntities")]
    partial class FixEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AanvoerderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlokLocatie")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumPrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Potmaat")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Steellengte")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Veildatum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VeilingProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.ToTable("Aanmeldingen", (string)null);
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Veildag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veildagen");
                });

            modelBuilder.Entity("VeilingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AanmeldingId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HuidigePrijs")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerkocht")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KoperId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StartPrijs")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeilingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volgorde")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AanmeldingId")
                        .IsUnique();

                    b.HasIndex("KoperId");

                    b.HasIndex("VeilingId");

                    b.ToTable("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Aanvoerders", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoperId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeilingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.HasIndex("VeilingId");

                    b.HasIndex("VeilingProductId");

                    b.ToTable("Biedingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Kopers", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EindTijd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HuidigProductId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAfgesloten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGestart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPauze")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HuidigProductId");

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veilingmeester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Veilingmeesters");
                });

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("Aanmeldingen")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("VeilingProduct", b =>
                {
                    b.HasOne("Aanmelding", "Aanmelding")
                        .WithOne("VeilingProduct")
                        .HasForeignKey("VeilingProduct", "AanmeldingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Koper", "Koper")
                        .WithMany()
                        .HasForeignKey("KoperId");

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("Producten")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aanmelding");

                    b.Navigation("Koper");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.HasOne("Gebruiker", "Gebruiker")
                        .WithOne("Aanvoerder")
                        .HasForeignKey("Veilingklok.Core.Entities.Aanvoerder", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bod", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Koper", "Koper")
                        .WithMany()
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", null)
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeilingProduct", "VeilingProduct")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.HasOne("Gebruiker", "Gebruiker")
                        .WithOne("Koper")
                        .HasForeignKey("Veilingklok.Core.Entities.Koper", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.HasOne("VeilingProduct", "HuidigProduct")
                        .WithMany()
                        .HasForeignKey("HuidigProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HuidigProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veilingmeester", b =>
                {
                    b.HasOne("Gebruiker", "Gebruiker")
                        .WithOne("Veilingmeester")
                        .HasForeignKey("Veilingklok.Core.Entities.Veilingmeester", "GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Navigation("Aanvoerder");

                    b.Navigation("Koper");

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("VeilingProduct", b =>
                {
                    b.Navigation("Biedingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Navigation("Aanmeldingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("Producten");
                });
#pragma warning restore 612, 618
        }
    }
}
