// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veilingklok.Infrastructure.Database;

#nullable disable

namespace Veilingklok.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251130211106_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Aanvoerders", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorGebruikerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorGebruikerId");

                    b.HasIndex("VeilingId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KoperId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlacedByGebruikerId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.Property<int>("VeilingProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.HasIndex("PlacedByGebruikerId");

                    b.HasIndex("VeilingId");

                    b.HasIndex("VeilingProductId");

                    b.ToTable("Biedingen", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Kopers", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AanvoerderId")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Categorie")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.ToTable("Producten", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentVeilingProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EindTijdUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTijdUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVeilingProductId");

                    b.ToTable("Veilingen", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AanvoerderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.Property<decimal>("HuidigePrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SoldToKoperId")
                        .HasColumnType("int");

                    b.Property<decimal>("StartPrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SoldToKoperId");

                    b.HasIndex("VeilingId", "Volgorde")
                        .IsUnique();

                    b.ToTable("VeilingProducten", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("Aanvoerder")
                        .HasForeignKey("Veilingklok.Core.Entities.Aanvoerder", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.AuditEntry", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "ActorGebruiker")
                        .WithMany()
                        .HasForeignKey("ActorGebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("AuditEntries")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorGebruiker");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bid", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Koper", "Koper")
                        .WithMany("Bids")
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "PlacedByGebruiker")
                        .WithMany()
                        .HasForeignKey("PlacedByGebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("Bids")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "VeilingProduct")
                        .WithMany("Bids")
                        .HasForeignKey("VeilingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("PlacedByGebruiker");

                    b.Navigation("Veiling");

                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("Koper")
                        .HasForeignKey("Veilingklok.Core.Entities.Koper", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("Producten")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "CurrentVeilingProduct")
                        .WithMany()
                        .HasForeignKey("CurrentVeilingProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentVeilingProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Veilingklok.Core.Entities.Product", "Product")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Koper", "SoldToKoper")
                        .WithMany("GekochteVeilingProducten")
                        .HasForeignKey("SoldToKoperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aanvoerder");

                    b.Navigation("Product");

                    b.Navigation("SoldToKoper");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Navigation("Producten");

                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Gebruiker", b =>
                {
                    b.Navigation("Aanvoerder");

                    b.Navigation("Koper");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("GekochteVeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Bids");

                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
