// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veilingklok.Infrastructure.Database;

#nullable disable

namespace Veilingklok.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251208002836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Aanvoerders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "jan@aanvoerder.com",
                            GebruikerId = 2,
                            Naam = "Jan Aanvoerder"
                        });
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorGebruikerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorGebruikerId");

                    b.HasIndex("VeilingId", "CreatedAtUtc");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KoperId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlacedByGebruikerId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.Property<int>("VeilingProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.HasIndex("PlacedByGebruikerId");

                    b.HasIndex("VeilingId");

                    b.HasIndex("VeilingProductId", "PlacedAtUtc");

                    b.ToTable("Biedingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achternaam = "Meester",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vm1@example.com",
                            PasswordHash = "dm0tc2VlZC1zYWx0LTAwMA==.KRqeXLGmj1DryTFBWCId0sZltd6nURyxHIqdjAmoXIo=",
                            Role = 3,
                            Username = "vm1",
                            Voornaam = "Veiling"
                        },
                        new
                        {
                            Id = 2,
                            Achternaam = "Aanvoerder",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "aanvoerder1@example.com",
                            PasswordHash = "YXYtc2VlZC1zYWx0LTAwMA==.tyfrGs1Ns/tRy5ChiEVBJlLHs3wqTLN3d24QNeJYzJs=",
                            Role = 2,
                            Username = "aanvoerder1",
                            Voornaam = "Jan"
                        },
                        new
                        {
                            Id = 3,
                            Achternaam = "Koper",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "koper1@example.com",
                            PasswordHash = "a3Atc2VlZC1zYWx0LTAwMA==.2ymdEbIJ9G+5O0/M/fT6jrS2ZRHYV3pzBK/2nW/BYco=",
                            Role = 1,
                            Username = "koper1",
                            Voornaam = "Klaas"
                        });
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Kopers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GebruikerId = 3,
                            Naam = "Klaas Koper",
                            Saldo = 500m
                        });
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AanvoerderId")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoeveelheidStuks")
                        .HasColumnType("int");

                    b.Property<string>("KlokLocatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinimumPrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PotmaatOfSteellengte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VeilDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.ToTable("Producten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AanvoerderId = 1,
                            Beschrijving = "Frisse mix alstroemeria's",
                            Categorie = "Bloemen",
                            FotoUrl = "/img/products/alstroemeria-mix.jpg",
                            HoeveelheidStuks = 50,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 4m,
                            Naam = "Alstroemeria Mix",
                            PotmaatOfSteellengte = "60cm",
                            Soort = "Bloem",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AanvoerderId = 1,
                            Beschrijving = "Dieprode anthurium",
                            Categorie = "Planten",
                            FotoUrl = "/img/products/anthurium-rood.jpg",
                            HoeveelheidStuks = 15,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 8m,
                            Naam = "Anthurium Rood",
                            PotmaatOfSteellengte = "14cm pot",
                            Soort = "Plant",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AanvoerderId = 1,
                            Beschrijving = "Vrolijke mix van gerbera's",
                            Categorie = "Boeket",
                            FotoUrl = "/img/products/boeket-gerbera-mix.jpg",
                            HoeveelheidStuks = 30,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 5m,
                            Naam = "Boeket Gerbera Mix",
                            PotmaatOfSteellengte = "n.v.t.",
                            Soort = "Boeket",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AanvoerderId = 1,
                            Beschrijving = "Luxe ranunculus-mix premium",
                            Categorie = "Boeket",
                            FotoUrl = "/img/products/boeket-ranunculus-mix-premium.jpg",
                            HoeveelheidStuks = 25,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 9m,
                            Naam = "Boeket Ranunculus Mix Premium",
                            PotmaatOfSteellengte = "n.v.t.",
                            Soort = "Boeket",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AanvoerderId = 1,
                            Beschrijving = "Oranje calla lelies",
                            Categorie = "Bloemen",
                            FotoUrl = "/img/products/calla-lily-oranje.jpg",
                            HoeveelheidStuks = 40,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 7m,
                            Naam = "Calla Lily Oranje",
                            PotmaatOfSteellengte = "55cm",
                            Soort = "Bloem",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AanvoerderId = 1,
                            Beschrijving = "Grote ficus lyrata kamerplant",
                            Categorie = "Planten",
                            FotoUrl = "/img/products/ficus-lyrata.jpg",
                            HoeveelheidStuks = 10,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 15m,
                            Naam = "Ficus Lyrata",
                            PotmaatOfSteellengte = "24cm pot",
                            Soort = "Plant",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AanvoerderId = 1,
                            Beschrijving = "Luchtige witte gypsophila",
                            Categorie = "Bloemen",
                            FotoUrl = "/img/products/gypsophila-paniculata-wit.jpg",
                            HoeveelheidStuks = 40,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 3m,
                            Naam = "Gypsophila Paniculata Wit",
                            PotmaatOfSteellengte = "70cm",
                            Soort = "Bloem",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AanvoerderId = 1,
                            Beschrijving = "Elegante witte orchidee",
                            Categorie = "Planten",
                            FotoUrl = "/img/products/orchidee-phalaenopsis-wit.jpg",
                            HoeveelheidStuks = 20,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 12m,
                            Naam = "Orchidee Phalaenopsis Wit",
                            PotmaatOfSteellengte = "12cm pot",
                            Soort = "Plant",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AanvoerderId = 1,
                            Beschrijving = "Sterke sansevieria zeylanica",
                            Categorie = "Planten",
                            FotoUrl = "/img/products/sansevieria-zeylanica.jpg",
                            HoeveelheidStuks = 25,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 10m,
                            Naam = "Sansevieria Zeylanica",
                            PotmaatOfSteellengte = "17cm pot",
                            Soort = "Plant",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AanvoerderId = 1,
                            Beschrijving = "Warm seizoensboeket in herfsttinten",
                            Categorie = "Boeket",
                            FotoUrl = "/img/products/seizoensboeket-herfst-mix.jpg",
                            HoeveelheidStuks = 30,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 14m,
                            Naam = "Seizoensboeket Herfst Mix",
                            PotmaatOfSteellengte = "n.v.t.",
                            Soort = "Boeket",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AanvoerderId = 1,
                            Beschrijving = "Dubbelbloemige tulpenmix",
                            Categorie = "Bloemen",
                            FotoUrl = "/img/products/tulpen-dubbelbloemig-mix.jpg",
                            HoeveelheidStuks = 50,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 6m,
                            Naam = "Tulpen Dubbelbloemig Mix",
                            PotmaatOfSteellengte = "40cm",
                            Soort = "Bloem",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            AanvoerderId = 1,
                            Beschrijving = "Licht boeket met witte rozen en lisianthus",
                            Categorie = "Boeket",
                            FotoUrl = "/img/products/White-Rose-Lisianthus-Bouquet.jpg",
                            HoeveelheidStuks = 20,
                            KlokLocatie = "Aalsmeer",
                            MinimumPrijs = 18m,
                            Naam = "White Rose Lisianthus Boeket",
                            PotmaatOfSteellengte = "n.v.t.",
                            Soort = "Boeket",
                            VeilDatum = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("VMs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GebruikerId = 1,
                            Naam = "Veiling Meester"
                        });
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentVeilingProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EindTijdUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Locatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartTijdUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VMId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVeilingProductId")
                        .IsUnique()
                        .HasFilter("[CurrentVeilingProductId] IS NOT NULL");

                    b.HasIndex("VMId");

                    b.ToTable("Veilingen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            EindTijdUtc = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Locatie = "Aalsmeer",
                            Naam = "Ochtendveiling Aalsmeer",
                            StartTijdUtc = new DateTime(2025, 1, 1, 8, 10, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VMId = 1
                        });
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AanvoerderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.Property<decimal>("HuidigePrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SoldToKoperId")
                        .HasColumnType("int");

                    b.Property<decimal>("StartPrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SoldToKoperId");

                    b.HasIndex("VeilingId", "Status", "Volgorde");

                    b.ToTable("VeilingProducten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AanvoerderId = 1,
                            Hoeveelheid = 50,
                            HuidigePrijs = 10m,
                            ProductId = 1,
                            StartPrijs = 10m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 1
                        },
                        new
                        {
                            Id = 2,
                            AanvoerderId = 1,
                            Hoeveelheid = 15,
                            HuidigePrijs = 15m,
                            ProductId = 2,
                            StartPrijs = 15m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 2
                        },
                        new
                        {
                            Id = 3,
                            AanvoerderId = 1,
                            Hoeveelheid = 30,
                            HuidigePrijs = 12m,
                            ProductId = 3,
                            StartPrijs = 12m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 3
                        },
                        new
                        {
                            Id = 4,
                            AanvoerderId = 1,
                            Hoeveelheid = 25,
                            HuidigePrijs = 18m,
                            ProductId = 4,
                            StartPrijs = 18m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 4
                        },
                        new
                        {
                            Id = 5,
                            AanvoerderId = 1,
                            Hoeveelheid = 40,
                            HuidigePrijs = 14m,
                            ProductId = 5,
                            StartPrijs = 14m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 5
                        },
                        new
                        {
                            Id = 6,
                            AanvoerderId = 1,
                            Hoeveelheid = 10,
                            HuidigePrijs = 30m,
                            ProductId = 6,
                            StartPrijs = 30m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 6
                        },
                        new
                        {
                            Id = 7,
                            AanvoerderId = 1,
                            Hoeveelheid = 40,
                            HuidigePrijs = 8m,
                            ProductId = 7,
                            StartPrijs = 8m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 7
                        },
                        new
                        {
                            Id = 8,
                            AanvoerderId = 1,
                            Hoeveelheid = 20,
                            HuidigePrijs = 24m,
                            ProductId = 8,
                            StartPrijs = 24m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 8
                        },
                        new
                        {
                            Id = 9,
                            AanvoerderId = 1,
                            Hoeveelheid = 25,
                            HuidigePrijs = 20m,
                            ProductId = 9,
                            StartPrijs = 20m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 9
                        },
                        new
                        {
                            Id = 10,
                            AanvoerderId = 1,
                            Hoeveelheid = 30,
                            HuidigePrijs = 28m,
                            ProductId = 10,
                            StartPrijs = 28m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 10
                        },
                        new
                        {
                            Id = 11,
                            AanvoerderId = 1,
                            Hoeveelheid = 50,
                            HuidigePrijs = 16m,
                            ProductId = 11,
                            StartPrijs = 16m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 11
                        },
                        new
                        {
                            Id = 12,
                            AanvoerderId = 1,
                            Hoeveelheid = 20,
                            HuidigePrijs = 32m,
                            ProductId = 12,
                            StartPrijs = 32m,
                            Status = 0,
                            VeilingId = 1,
                            Volgorde = 12
                        });
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("Aanvoerder")
                        .HasForeignKey("Veilingklok.Core.Entities.Aanvoerder", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.AuditEntry", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "ActorGebruiker")
                        .WithMany()
                        .HasForeignKey("ActorGebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("AuditEntries")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorGebruiker");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bid", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Koper", "Koper")
                        .WithMany("Bids")
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "PlacedByGebruiker")
                        .WithMany()
                        .HasForeignKey("PlacedByGebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("Bids")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "VeilingProduct")
                        .WithMany("Bids")
                        .HasForeignKey("VeilingProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("PlacedByGebruiker");

                    b.Navigation("Veiling");

                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("Koper")
                        .HasForeignKey("Veilingklok.Core.Entities.Koper", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("Producten")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VM", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("VM")
                        .HasForeignKey("Veilingklok.Core.Entities.VM", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "CurrentVeilingProduct")
                        .WithOne()
                        .HasForeignKey("Veilingklok.Core.Entities.Veiling", "CurrentVeilingProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Veilingklok.Core.Entities.VM", "VM")
                        .WithMany("Veilingen")
                        .HasForeignKey("VMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentVeilingProduct");

                    b.Navigation("VM");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.Product", "Product")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Koper", "SoldToKoper")
                        .WithMany("GekochteVeilingProducten")
                        .HasForeignKey("SoldToKoperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aanvoerder");

                    b.Navigation("Product");

                    b.Navigation("SoldToKoper");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Navigation("Producten");

                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Gebruiker", b =>
                {
                    b.Navigation("Aanvoerder");

                    b.Navigation("Koper");

                    b.Navigation("VM");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("GekochteVeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VM", b =>
                {
                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Bids");

                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
