// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veilingklok.Infrastructure.Database;

#nullable disable

namespace Veilingklok.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20260115161706_WerkMf")]
    partial class WerkMf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AanvoerderId")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.Property<int>("KlokLocatie")
                        .HasColumnType("int");

                    b.Property<DateTime>("LeverDatum")
                        .HasColumnType("date");

                    b.Property<decimal>("MinimumPrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Potmaat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Steellengte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VeilingProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.ToTable("Aanmeldingen", (string)null);
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Transactie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int?>("KoperId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("datetime2");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.Property<int>("VeilingProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.HasIndex("VeilingProductId");

                    b.ToTable("Transacties", (string)null);
                });

            modelBuilder.Entity("Veildag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Veildagen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Aanvoerders", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("KoperId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("datetime2");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.Property<int>("VeilingProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.HasIndex("VeilingId");

                    b.HasIndex("VeilingProductId");

                    b.ToTable("Biedingen", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Kopers", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AanvoerderId")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoeveelheidStuks")
                        .HasColumnType("int");

                    b.Property<string>("KlokLocatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinimumPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PotmaatOfSteellengte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VeilDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.ToTable("Producten", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AfgeslotenOpUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EindTijd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HuidigProductId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTijd")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HuidigProductId");

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AanmeldingId")
                        .HasColumnType("int");

                    b.Property<decimal>("DalingPerSeconde")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HuidigePrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDoorgedraaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerkocht")
                        .HasColumnType("bit");

                    b.Property<int?>("KoperId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LaatstePrijsUpdateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ResterendeHoeveelheid")
                        .HasColumnType("int");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AanmeldingId")
                        .IsUnique();

                    b.HasIndex("KoperId");

                    b.HasIndex("VeilingId");

                    b.ToTable("VeilingProducten", (string)null);
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veilingmeester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Veilingmeesters", (string)null);
                });

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("Aanmeldingen")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("Transactie", b =>
                {
                    b.HasOne("Gebruiker", "Koper")
                        .WithMany()
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "VeilingProduct")
                        .WithMany("Transacties")
                        .HasForeignKey("VeilingProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.HasOne("Gebruiker", "Gebruiker")
                        .WithOne("Aanvoerder")
                        .HasForeignKey("Veilingklok.Core.Entities.Aanvoerder", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bod", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Koper", "Koper")
                        .WithMany()
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "VeilingProduct")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("Veiling");

                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.HasOne("Gebruiker", "Gebruiker")
                        .WithOne("Koper")
                        .HasForeignKey("Veilingklok.Core.Entities.Koper", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany()
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "HuidigProduct")
                        .WithMany()
                        .HasForeignKey("HuidigProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HuidigProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.HasOne("Aanmelding", "Aanmelding")
                        .WithOne("VeilingProduct")
                        .HasForeignKey("Veilingklok.Core.Entities.VeilingProduct", "AanmeldingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Koper", "Koper")
                        .WithMany()
                        .HasForeignKey("KoperId");

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("Producten")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aanmelding");

                    b.Navigation("Koper");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veilingmeester", b =>
                {
                    b.HasOne("Gebruiker", "Gebruiker")
                        .WithOne("Veilingmeester")
                        .HasForeignKey("Veilingklok.Core.Entities.Veilingmeester", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Aanmelding", b =>
                {
                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Navigation("Aanvoerder");

                    b.Navigation("Koper");

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Navigation("Aanmeldingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("Producten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("Transacties");
                });
#pragma warning restore 612, 618
        }
    }
}
