// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veilingklok.Infrastructure.Database;

#nullable disable

namespace Veilingklok.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("TEXT");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Aanvoerders");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorGebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeilingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorGebruikerId");

                    b.HasIndex("VeilingId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KoperId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlacedByGebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.HasIndex("PlacedByGebruikerId");

                    b.HasIndex("VeilingId");

                    b.HasIndex("VeilingProductId");

                    b.ToTable("Biedingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("Kopers");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AanvoerderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoeveelheidStuks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KlokLocatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumPrijs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PotmaatOfSteellengte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VeilDatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.ToTable("Producten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.ToTable("VMs");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentVeilingProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EindTijdUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locatie")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("StartTijdUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VMId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVeilingProductId")
                        .IsUnique();

                    b.HasIndex("VMId");

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AanvoerderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HuidigePrijs")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoldToKoperId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StartPrijs")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volgorde")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AanvoerderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SoldToKoperId");

                    b.HasIndex("VeilingId");

                    b.ToTable("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("Aanvoerder")
                        .HasForeignKey("Veilingklok.Core.Entities.Aanvoerder", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.AuditEntry", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "ActorGebruiker")
                        .WithMany()
                        .HasForeignKey("ActorGebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("AuditEntries")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorGebruiker");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Bid", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Koper", "Koper")
                        .WithMany("Bids")
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "PlacedByGebruiker")
                        .WithMany()
                        .HasForeignKey("PlacedByGebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("Bids")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "VeilingProduct")
                        .WithMany("Bids")
                        .HasForeignKey("VeilingProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("PlacedByGebruiker");

                    b.Navigation("Veiling");

                    b.Navigation("VeilingProduct");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("Koper")
                        .HasForeignKey("Veilingklok.Core.Entities.Koper", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("Producten")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VM", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("VM")
                        .HasForeignKey("Veilingklok.Core.Entities.VM", "GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.VeilingProduct", "CurrentVeilingProduct")
                        .WithOne()
                        .HasForeignKey("Veilingklok.Core.Entities.Veiling", "CurrentVeilingProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.VM", "VM")
                        .WithMany("Veilingen")
                        .HasForeignKey("VMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentVeilingProduct");

                    b.Navigation("VM");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.HasOne("Veilingklok.Core.Entities.Aanvoerder", "Aanvoerder")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilingklok.Core.Entities.Product", "Product")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilingklok.Core.Entities.Koper", "SoldToKoper")
                        .WithMany("GekochteVeilingProducten")
                        .HasForeignKey("SoldToKoperId");

                    b.HasOne("Veilingklok.Core.Entities.Veiling", "Veiling")
                        .WithMany("VeilingProducten")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aanvoerder");

                    b.Navigation("Product");

                    b.Navigation("SoldToKoper");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Aanvoerder", b =>
                {
                    b.Navigation("Producten");

                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Gebruiker", b =>
                {
                    b.Navigation("Aanvoerder");

                    b.Navigation("Koper");

                    b.Navigation("VM");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Koper", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("GekochteVeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Product", b =>
                {
                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VM", b =>
                {
                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.Veiling", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Bids");

                    b.Navigation("VeilingProducten");
                });

            modelBuilder.Entity("Veilingklok.Core.Entities.VeilingProduct", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
